apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydepool
  labels:
    app: game
spec:
  replicas: 5
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
        - name: cont7
          image: yaseenbasha/game
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mysvc5
spec:
  type: NodePort
  selector:
    app: game
  ports:
    - port: 80
      targetPort: 80

